### ISSUE TITLE
mead aging problem with automate

### ISSUE THREAD

**Issue by kamigari84** [SwizzyStudios/SV-SwizzysDistillery-CFR#10]
I am having an issue with this mod and automate where auto-aging your 'special' meads retrieved the item at normal quality after having already passed gold and supposedly reached iridium. Regular mead auto-ages normally, and your varieties can be harvested manually at iridium quality by disconnecting them from any chests ... any idea where the issue could lay? Should I ask automate's or CFR's authors?

**Comment by SwizzyStudios** [comment]
Thanks for opening an issue.  It's likely automate.  I've talked to pathos about a few of these things and it's just one of those things.  I'll look into it on my end and see if there is something that can be done.

**Comment by SwizzyStudios** [comment]
I tried to replicate this but only changing the IDs in my manifest resulted in this.  I did notice that the CFR on nexus mod has a few others running into this issue.  
![image](https://user-images.githubusercontent.com/46543438/52758017-5fe22200-2fcc-11e9-8dca-1873615b6b71.png)

**Comment by SwizzyStudios** [comment]
I also noticed that the 2.10.10 version was pulled from Nexus Mods and that 2.10.9 is the latest available.  My suggestion is to downgrade.
![image](https://user-images.githubusercontent.com/46543438/52758112-be0f0500-2fcc-11e9-9fb2-942740345b9c.png)

**Comment by SwizzyStudios** [comment]
Good news I was able to replicate it. Bad news looks like it might be a Automate.  I am going to reach out to the author.

**Comment by SwizzyStudios** [comment]
For tracking purposes.
https://github.com/Pathoschild/StardewMods/issues/375

**Comment by kamigari84** [comment]
Would the fact I can't split stacks of your brews without the [split-off part resetting to normal quality](https://github.com/SwizzyStudios/SV-SwizzysDistillery-CFR/issues/9#issuecomment-463656592) have nothing to do with this then?

**Comment by Pathoschild** [comment]
I think that's related. It sounds like CFR's custom items aren't correctly keeping their quality when the item is cloned.

**Comment by SwizzyStudios** [comment]
@kamigari84 closing this issue since Pathoschild was able to confirm it isn't Automate but CFR.
