### ISSUE TITLE
Distillery turns into chests after sleeping for the day

### ISSUE THREAD

**Issue by k3rizz3k** [SwizzyStudios/SV-SwizzysDistillery-CFR#6]
My distillery turns into a chest after a day or two, while I'm sleeping.

**Comment by SwizzyStudios** [comment]
Than you for creating an issue.  Please answer the following if you can...

What other mods are you playing with?

Did you download the first version of my mod then upgrade?

Does this happen to all the distilleries? Do new ones from Gus look like chests?

If you download the CJB Item Spawner mod can you find the distillery and does it look fine?

I have attempted to recreate but never ran into this issue.  More details from above questions will help troubleshoot.

**Comment by SwizzyStudios** [comment]
More information find from another user. https://log.smapi.io/8c2ui9Pg?raw=true.

Will look into this now.

**Comment by SwizzyStudios** [comment]
I tried to replicate this but only changing the IDs in my manifest resulted in this.  I did notice that the CFR on nexus mod has a few others running into this issue.  
![image](https://user-images.githubusercontent.com/46543438/52758017-5fe22200-2fcc-11e9-8dca-1873615b6b71.png)

**Comment by SwizzyStudios** [comment]
I also noticed that the 2.10.10 version was pulled from Nexus Mods and that 2.10.9 is the latest available.  My suggestion is to downgrade.
![image](https://user-images.githubusercontent.com/46543438/52758112-be0f0500-2fcc-11e9-9fb2-942740345b9c.png)

**Comment by SwizzyStudios** [comment]
Closing the issue as it is Custom Farming Redux bug

**Comment by k3rizz3k** [comment]
Thank you for looking into it. I'll downgrade
