### ISSUE TITLE
mead turning into chests after loading the save

### ISSUE THREAD

**Issue by kamigari84** [SwizzyStudios/SV-SwizzysDistillery-CFR#9]
the "PyTK Rebuilding Custom Objects from Save" seems to fail
my log: https://log.smapi.io/8c2ui9Pg ... sorry about the extra clutter in there

P.S. I am also having an issue with this mod and automate where auto-aging your 'special' meads returned the item at normal quality when supposedly at iridium, causing a loop.

**Comment by SwizzyStudios** [comment]
Thanks.  It's possible I'm doing something wrong with pytk. I will investigate.

**Comment by SwizzyStudios** [comment]
I tried to replicate this but only changing the IDs in my manifest resulted in this.  I did notice that the CFR on nexus mod has a few others running into this issue.  
![image](https://user-images.githubusercontent.com/46543438/52758017-5fe22200-2fcc-11e9-8dca-1873615b6b71.png)

**Comment by SwizzyStudios** [comment]
I also noticed that the 2.10.10 version was pulled from Nexus Mods and that 2.10.9 is the latest available.  My suggestion is to downgrade.
![image](https://user-images.githubusercontent.com/46543438/52758112-be0f0500-2fcc-11e9-9fb2-942740345b9c.png)

**Comment by kamigari84** [comment]
Another possibly related issue: sometimes (re)loading a save resets any/all of your brews to normal quality;  This also happens, much more consistently, when splitting a stack of any of your brews.

P.S. I do have v2.10.9 of CFAutomate installed, but had edited its manifest to suppress a false update-available message from smapi. Sorry for the confusion.

**Comment by SwizzyStudios** [comment]
The version was just a suggestion not really a fix...though I wish it did solve all your problems.

Splitting a stack sounds like CFR but I will investigate.  Likely outcome would be a new mod just for the mead to work with Automate..correctly as this CFAutomate/CFR doesn't seem to do what we all want.

For the save resets/reloads is the quality lost in the casks or in inventories...or both?

**Comment by kamigari84** [comment]
I meant in inventories.
I will have to check if that also happens in the casks, as I don't quite recall right now.

**Comment by SwizzyStudios** [comment]
@kamigari84 closing this issue since Pathoschild was able to confirm it isn't Automate but CFR, he opened an issue with CFR developer.
